"""Add USER role to UserRole enum

Revision ID: 781becafb060
Revises: cdea4954c61b
Create Date: 2025-09-13 18:29:53.291790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781becafb060'
down_revision: Union[str, None] = 'cdea4954c61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add USER value to the UserRole enum
    op.execute("ALTER TYPE userrole ADD VALUE 'USER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values, 
    # so we cannot easily downgrade this migration
    pass
    # ### end Alembic commands ###
